// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	douyin_api "ByteTech-7355608/douyin-server/cmd/api/biz/router/douyin/api"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	douyin_api.Register(r)
}
