// Code generated by Kitex v0.4.4. DO NOT EDIT.

package baseservice

import (
	base "ByteTech-7355608/douyin-server/kitex_gen/douyin/base"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Feed(ctx context.Context, req *base.DouyinFeedRequest, callOptions ...callopt.Option) (r *base.DouyinFeedResponse, err error)
	UserRegister(ctx context.Context, req *base.DouyinUserRegisterRequest, callOptions ...callopt.Option) (r *base.DouyinUserRegisterResponse, err error)
	UserLogin(ctx context.Context, req *base.DouyinUserLoginRequest, callOptions ...callopt.Option) (r *base.DouyinUserLoginResponse, err error)
	UserMsg(ctx context.Context, req *base.DouyinUserRequest, callOptions ...callopt.Option) (r *base.DouyinUserResponse, err error)
	PublishAction(ctx context.Context, req *base.DouyinPublishActionRequest, callOptions ...callopt.Option) (r *base.DouyinPublishActionResponse, err error)
	PublishList(ctx context.Context, req *base.DouyinPublishListRequest, callOptions ...callopt.Option) (r *base.DouyinPublishListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kBaseServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kBaseServiceClient struct {
	*kClient
}

func (p *kBaseServiceClient) Feed(ctx context.Context, req *base.DouyinFeedRequest, callOptions ...callopt.Option) (r *base.DouyinFeedResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Feed(ctx, req)
}

func (p *kBaseServiceClient) UserRegister(ctx context.Context, req *base.DouyinUserRegisterRequest, callOptions ...callopt.Option) (r *base.DouyinUserRegisterResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserRegister(ctx, req)
}

func (p *kBaseServiceClient) UserLogin(ctx context.Context, req *base.DouyinUserLoginRequest, callOptions ...callopt.Option) (r *base.DouyinUserLoginResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserLogin(ctx, req)
}

func (p *kBaseServiceClient) UserMsg(ctx context.Context, req *base.DouyinUserRequest, callOptions ...callopt.Option) (r *base.DouyinUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserMsg(ctx, req)
}

func (p *kBaseServiceClient) PublishAction(ctx context.Context, req *base.DouyinPublishActionRequest, callOptions ...callopt.Option) (r *base.DouyinPublishActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishAction(ctx, req)
}

func (p *kBaseServiceClient) PublishList(ctx context.Context, req *base.DouyinPublishListRequest, callOptions ...callopt.Option) (r *base.DouyinPublishListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishList(ctx, req)
}
