// Code generated by Kitex v0.4.4. DO NOT EDIT.

package socialservice

import (
	social "ByteTech-7355608/douyin-server/kitex_gen/douyin/social"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	FollowAction(ctx context.Context, req *social.DouyinFollowActionRequest, callOptions ...callopt.Option) (r *social.DouyinFollowActionResponse, err error)
	FollowList(ctx context.Context, req *social.DouyinFollowingListRequest, callOptions ...callopt.Option) (r *social.DouyinFollowingListResponse, err error)
	FollowerList(ctx context.Context, req *social.DouyinFollowerListRequest, callOptions ...callopt.Option) (r *social.DouyinFollowerListResponse, err error)
	FriendList(ctx context.Context, req *social.DouyinRelationFriendListRequest, callOptions ...callopt.Option) (r *social.DouyinRelationFriendListResponse, err error)
	MessageList(ctx context.Context, req *social.DouyinMessageChatRequest, callOptions ...callopt.Option) (r *social.DouyinMessageChatResponse, err error)
	SendMessage(ctx context.Context, req *social.DouyinMessageActionRequest, callOptions ...callopt.Option) (r *social.DouyinMessageActionResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kSocialServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kSocialServiceClient struct {
	*kClient
}

func (p *kSocialServiceClient) FollowAction(ctx context.Context, req *social.DouyinFollowActionRequest, callOptions ...callopt.Option) (r *social.DouyinFollowActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowAction(ctx, req)
}

func (p *kSocialServiceClient) FollowList(ctx context.Context, req *social.DouyinFollowingListRequest, callOptions ...callopt.Option) (r *social.DouyinFollowingListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowList(ctx, req)
}

func (p *kSocialServiceClient) FollowerList(ctx context.Context, req *social.DouyinFollowerListRequest, callOptions ...callopt.Option) (r *social.DouyinFollowerListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowerList(ctx, req)
}

func (p *kSocialServiceClient) FriendList(ctx context.Context, req *social.DouyinRelationFriendListRequest, callOptions ...callopt.Option) (r *social.DouyinRelationFriendListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FriendList(ctx, req)
}

func (p *kSocialServiceClient) MessageList(ctx context.Context, req *social.DouyinMessageChatRequest, callOptions ...callopt.Option) (r *social.DouyinMessageChatResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MessageList(ctx, req)
}

func (p *kSocialServiceClient) SendMessage(ctx context.Context, req *social.DouyinMessageActionRequest, callOptions ...callopt.Option) (r *social.DouyinMessageActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendMessage(ctx, req)
}
