// Code generated by MockGen. DO NOT EDIT.
// Source: kitex_gen/douyin/interaction/interactionservice/client.go

// Package interactioncli is a generated GoMock package.
package interactioncli

import (
	interaction "ByteTech-7355608/douyin-server/kitex_gen/douyin/interaction"
	context "context"
	reflect "reflect"

	callopt "github.com/cloudwego/kitex/client/callopt"
	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CommentAction mocks base method.
func (m *MockClient) CommentAction(ctx context.Context, req *interaction.DouyinCommentActionRequest, callOptions ...callopt.Option) (*interaction.DouyinCommentActionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, req}
	for _, a := range callOptions {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommentAction", varargs...)
	ret0, _ := ret[0].(*interaction.DouyinCommentActionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommentAction indicates an expected call of CommentAction.
func (mr *MockClientMockRecorder) CommentAction(ctx, req interface{}, callOptions ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, req}, callOptions...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommentAction", reflect.TypeOf((*MockClient)(nil).CommentAction), varargs...)
}

// CommentList mocks base method.
func (m *MockClient) CommentList(ctx context.Context, req *interaction.DouyinCommentListRequest, callOptions ...callopt.Option) (*interaction.DouyinCommentListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, req}
	for _, a := range callOptions {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommentList", varargs...)
	ret0, _ := ret[0].(*interaction.DouyinCommentListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommentList indicates an expected call of CommentList.
func (mr *MockClientMockRecorder) CommentList(ctx, req interface{}, callOptions ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, req}, callOptions...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommentList", reflect.TypeOf((*MockClient)(nil).CommentList), varargs...)
}

// FavoriteAction mocks base method.
func (m *MockClient) FavoriteAction(ctx context.Context, req *interaction.DouyinFavoriteActionRequest, callOptions ...callopt.Option) (*interaction.DouyinFavoriteActionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, req}
	for _, a := range callOptions {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FavoriteAction", varargs...)
	ret0, _ := ret[0].(*interaction.DouyinFavoriteActionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FavoriteAction indicates an expected call of FavoriteAction.
func (mr *MockClientMockRecorder) FavoriteAction(ctx, req interface{}, callOptions ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, req}, callOptions...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FavoriteAction", reflect.TypeOf((*MockClient)(nil).FavoriteAction), varargs...)
}

// FavoriteList mocks base method.
func (m *MockClient) FavoriteList(ctx context.Context, req *interaction.DouyinFavoriteListRequest, callOptions ...callopt.Option) (*interaction.DouyinFavoriteListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, req}
	for _, a := range callOptions {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FavoriteList", varargs...)
	ret0, _ := ret[0].(*interaction.DouyinFavoriteListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FavoriteList indicates an expected call of FavoriteList.
func (mr *MockClientMockRecorder) FavoriteList(ctx, req interface{}, callOptions ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, req}, callOptions...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FavoriteList", reflect.TypeOf((*MockClient)(nil).FavoriteList), varargs...)
}
