// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt     time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt     soft_delete.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Username      string         `gorm:"column:username;not null" json:"username"`
	Password      string         `gorm:"column:password;not null" json:"password"`
	FollowCount   int64          `gorm:"column:follow_count" json:"follow_count"`
	FollowerCount int64          `gorm:"column:follower_count" json:"follower_count"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
